stages:
  - build
  - release

variables:
  APP_NAME: "VPCompare"

build_exe:
  stage: build
  tags:
    - WINDOWS
  script:

    # Créer le dossier de sortie
    - New-Item -ItemType Directory -Force -Path out

    # Construire le CLASSPATH (séparateur ; sous Windows)
    - $CLASSPATH = (Get-ChildItem lib -Filter *.jar -Recurse | ForEach-Object { $_.FullName }) -join ";"

    # Lister les sources Java
    - Get-ChildItem src -Filter *.java -Recurse | ForEach-Object { $_.FullName } > sources.txt

    # Compilation
    - javac -d out -cp "$CLASSPATH" @sources.txt

    # Copier les ressources (équivalent rsync)
    - Copy-Item src\* out -Recurse -Force -Exclude *.java

    # Création du JAR
    - jar cfe monapp.jar com.myapp.Main -C out .

    # Création de l'EXE Windows
    - jpackage `
        --input . `
        --main-jar monapp.jar `
        --name test `
        --type exe

  artifacts:
    paths:
      - "*.exe"

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release"
  release:
    tag_name: "$CI_COMMIT_TAG"
    name: "Release $CI_COMMIT_TAG"
    description: "Version $CI_COMMIT_TAG"
    assets:
      links:
        - name: "${APP_NAME}-${CI_COMMIT_TAG#v}.exe"
          url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/${APP_NAME}-${CI_COMMIT_TAG#v}.exe"
